name: TypeScript check
on:
  push:
    branches: ['master', 'dev']
  pull_request:
    branches: ['master', 'dev']
  workflow_dispatch:

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js ⚙️ - Cache dependencies ⚡ - Install dependencies 🔧
        uses: ./.github/actions/setup-node

      - name: TypeScript check
        run: pnpm run typecheck
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NEXT_PUBLIC_PUBLIC_URL: ${{ secrets.NEXT_PUBLIC_APP_URL }}
          APP_DOMAIN: ${{ secrets.APP_DOMAIN }}
          REDIS_HOST: ${{ secrets.REDIS_HOST }},
          ENABLE_SIGNUP_WITH_EMAIL: ${{ secrets.ENABLE_SIGNUP_WITH_EMAIL }},
          SMTP_HOST: ${{ secrets.SMTP_HOST }},
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
